[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
shared = { path = "../shared" }
lunatic = "0.7.0"
serde = { version = "1.0.117", features = ["derive"] }
dipa = { version = "0.1.1", features = ["derive"] }
bincode = "1.3.3"
