[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.117", features = ["derive"] }
dipa = { version = "0.1.1", features = ["derive"] }
